ALTER SESSION set "_ORACLE_SCRIPT" = true;


CREATE USER hugo IDENTIFIED BY hugo
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
PROFILE DEFAULT ACCOUNT UNLOCK;
ALTER USER hugo QUOTA UNLIMITED ON USERS;

GRANT CONNECT TO hugo;
GRANT RESOURCE TO hugo;
GRANT EXECUTE ON SYS.DBMS_LOCK TO hugo;
GRANT EXECUTE ON SYS.OWA_OPT_LOCK TO hugo;
GRANT CREATE ANY DIRECTORY TO hugo;


CREATE OR REPLACE DIRECTORY MYDIR AS 'C:\';
CREATE OR REPLACE DIRECTORY MYDIR AS 'D:\Ecole\B3\XML\Labo-XML\SGBD';